# Generated by Django 4.2.17 on 2025-02-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSecretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blood_secretary', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('secretary', 'Secretary'), ('blood_secretary', 'Blood Secretary'), ('member', 'Member')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_secretary', models.BooleanField(default=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member', models.BooleanField(default=True)),
                ('blood_secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bloodsecretary')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.secretary')),
            ],
        ),
        migrations.AddField(
            model_name='bloodsecretary',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
        migrations.AddField(
            model_name='bloodsecretary',
            name='secretary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.secretary'),
        ),
    ]
