# Generated by Django 4.2.17 on 2025-02-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_secretary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodsecretary',
            name='is_blood_secretary',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='is_secretary',
        ),
    ]
