# Generated by Django 4.2.17 on 2025-02-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bloodsecretary_user_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
