# Generated by Django 4.2.17 on 2025-02-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodsecretary',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
