# Generated by Django 4.2.17 on 2025-02-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_bloodsecretary_phone_alter_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretary',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
