# Generated by Django 4.2.17 on 2025-02-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(),
        ),
    ]
