# Generated by Django 4.2.17 on 2025-02-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_alter_donor_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
