# Generated by Django 4.2.17 on 2025-02-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
